### ISSUE TITLE
Bütün teqlərə class adı verməyə çalışın

### ISSUE THREAD

**Issue by isbendiyarovanezrin** [KheyransaPashayeva/PragmatechFoundationProject#10]
CSS-də `nav ul li a` yazmaq yerinə `a` teqinə class adı vermək daha oxunaqlı olmaz, sizcə? Məncə, elə olar. Məsələn, `nav-link` və ya elə adicə `link` adında class adı verə bilərsiniz. Həm yazılışı daha qısa olduğu üçün daha oxunaqlı olar, həm də bu class'dan başqa yerdə də istifadə edə bilərsiniz. Elə ən əsası da budur. Başqa yerdə istifadə edə bilmək.

**Comment by KheyransaPashayeva** [comment]
mlm ile isleyende ele basladigimiz ucun alternativlerden xeberim yox idi nezre alacam birde bundan evvel yazilan kodlari burdan silmeliyem qarismasin deye template deyisdiyi ucun men kompda silsemde burda qalir

**Comment by isbendiyarovanezrin** [comment]
Xeyr, silməyin, məncə. Başqa qovluqda yazsanız qarışmaz.
