### ISSUE TITLE
Teqlərə class adı verin

### ISSUE THREAD

**Issue by isbendiyarovanezrin** [KheyransaPashayeva/PragmatechFoundationProject#11]
[Bu](https://github.com/KheyransaPashayeva/PragmatechFoundationProject/blob/master/ProjectFrontEnd/GeoEco_com_sayt%C4%B1/home/css/home.css#L43) hissədə ` .info-bar-nav ul li a i` yazmaq yerinə  `i` teqinə [verdiyiniz](https://github.com/KheyransaPashayeva/PragmatechFoundationProject/blob/master/ProjectFrontEnd/GeoEco_com_sayt%C4%B1/home/index.html#L26) `<i class="fas fa-map-marker-alt">` class adından istifadə edin.

**Comment by isbendiyarovanezrin** [comment]
Bu class adları "Font Awesome"dən avtomatik olaraq gəlir, bilirəm, amma bunun yanına siz də istədiyiniz class adını yaza bilərsiniz.

**Comment by KheyransaPashayeva** [comment]
bunu bilmek isteyirdim eslinde yaxsi oldu
