### ISSUE TITLE
Bəzi xırda səhvlər

### ISSUE THREAD

**Issue by isbendiyarovanezrin** [KheyransaPashayeva/PragmatechFoundationProject#18]
**[Burada](https://github.com/KheyransaPashayeva/PragmatechFoundationProject/blob/master/ProjectFrontEnd/GeoEco_com_sayt%C4%B1/home/css/home.css#L145)** 1 vergül qoyulmalıdır.

**Comment by isbendiyarovanezrin** [comment]
CSS-də sətirlər arasında çoxlu ara, boşluq qoymaq oxunaqlılığı azaldır, səliqəsiz görünür. Məsələn, **[bu](https://github.com/KheyransaPashayeva/PragmatechFoundationProject/blob/master/ProjectFrontEnd/GeoEco_com_sayt%C4%B1/home/css/home.css#L162)** hissədəki kimi.

**Comment by isbendiyarovanezrin** [comment]
**[Burada](https://github.com/KheyransaPashayeva/PragmatechFoundationProject/blob/master/ProjectFrontEnd/GeoEco_com_sayt%C4%B1/home/css/home.css#L80)** da bir vergül olmalıdır.

**Comment by isbendiyarovanezrin** [comment]
**[Bu](https://github.com/KheyransaPashayeva/PragmatechFoundationProject/blob/master/ProjectFrontEnd/GeoEco_com_sayt%C4%B1/home/css/home.css#L164)** boyda ara buraxılmaz.

**Comment by KheyransaPashayeva** [comment]
salam bunlar copy paste ederken yaranmis sehvlerdir telesik push etdim gece fikir vermemisem duzeltim tesekkurler
