### ISSUE TITLE
Şəkil adlarına düzəliş edin

### ISSUE THREAD

**Issue by isbendiyarovanezrin** [KheyransaPashayeva/PragmatechFoundationProject#20]
Belə `background-image: url(../image/i\ \(5\).jpg);`  bir şəkil adı nə dərəcədə düzgündür, sizcə?

**Comment by KheyransaPashayeva** [comment]
İnternetden yuklediyim ucun ve onlar müvəqqəti olduğuna gore ele diqqət
yetirmemisdim problemi hell etdim

5 Ara 2021 Paz 15:56 tarihinde Nəzrin İsbəndiyarova <
***@***.***> şunu yazdı:
