### ISSUE TITLE
Bəzi xırda səhvlər

### ISSUE THREAD

**Issue by isbendiyarovanezrin** [KheyransaPashayeva/PragmatechFoundationProject#23]
**[Bu](https://github.com/KheyransaPashayeva/PragmatechFoundationProject/blob/master/Works/porto/navbar.css#L35)** kod sətri artıqdır.

**Comment by isbendiyarovanezrin** [comment]
Kodlar səliqəsiz yazılıb. "Prettier - Code formatter" adlı Visual Studio Code extensionu var. O kodları avtomatik olaraq səliqəyə salır. Ondan istifadə edə bilərsiniz.

**Comment by isbendiyarovanezrin** [comment]
`<meta name="viewport" content="width=, initial-scale=1.0">` bu sətir belə yazılmır. ❌ 
`<meta name="viewport" content="width=device-width, initial-scale=1.0">` belə yazılmalıdır. ✔️

**Comment by KheyransaPashayeva** [comment]
yazdiginiz hisseni html5 yazanda komp avtomatik verir el ile daxil etmirem ola biler sehven ne vaxtsa kursor ustunde olanda sehv yaranib
