### ISSUE TITLE
Fayl və qovluq strukturuna diqqət etmək lazımdır

### ISSUE THREAD

**Issue by isbendiyarovanezrin** [KheyransaPashayeva/PragmatechFoundationProject#24]
"Ad.js" adlı qovluğun içində "index.html" faylı var. Bu çox yanlışdır.

**Comment by KheyransaPashayeva** [comment]
ola biler sadece bir hefte olar baslamisiq javascripte ve visualda problemlerle qarsilasiriq mlm de bu cur yazdigina gore heleki bele davamedir yeqin oturaqlasandan sonra siz deyeni edecik

**Comment by isbendiyarovanezrin** [comment]
Müəllim də belə yazır? Yoxsa səhv oxudum?
