### ISSUE TITLE
"CoderCrunch" saytında maraqlı testlər işləyə bilərsiniz

### ISSUE THREAD

**Issue by isbendiyarovanezrin** [KheyransaPashayeva/PragmatechFoundationProject#27]
[**CoderCrunch**](https://www.codercrunch.com/quiz/search?skill=javascript) saytından istədiyiniz dilə uyğun (sol tərəfdən seçmək olur, çoxlu seçim var) test işləyə bilərsiniz. Sonda da nəticənizi göstərir (neçə düz, neçə səhv etdiyinizi). Sizin üçün maraqlı ola biləcəyini düşündüm. İşləyib özünüzü yoxlaya bilərsiniz.

**Comment by KheyransaPashayeva** [comment]
Bu tipli linkler paylassaz sevinerem

12 Ara 2021 Paz 18:36 tarihinde Nəzrin İsbəndiyarova <
***@***.***> şunu yazdı:

**Comment by isbendiyarovanezrin** [comment]
Tapdıqca paylaşaram.
