### ISSUE TITLE
Repoya "README.md" və "Research.md" adlı fayllar əlavə edin

### ISSUE THREAD

**Issue by isbendiyarovanezrin** [KheyransaPashayeva/PragmatechFoundationProject#3]
- README faylı nədir?
[Bu](https://www.mygreatlearning.com/blog/readme-file/) linkdən oxuya bilərsiniz.
- Research.md faylı nə üçündür? 
"Research.md" faylında, məsələn, müəllimin tapşırıq kimi verdiyi suallara cavab yaza bilərsiniz.

**Comment by KheyransaPashayeva** [comment]
Readme.md acmaq baresinde bir söz deyilmemisdi reseach var sadece work
papkasinin icinde oldugu ucun gormemisiniz

25 Kas 2021 Per 02:20 tarihinde Nəzrin İsbəndiyarova <
***@***.***> şunu yazdı:

**Comment by isbendiyarovanezrin** [comment]
İndi deyildi.🙂"Research.md" faylına gəldikdə isə "Works" qovluğunun içində olmalı deyil, onunla eyni sırada olmalıdır.
