### ISSUE TITLE
CSS faylları və şəkillər başqa bir qovluqda olmalıdır

### ISSUE THREAD

**Issue by isbendiyarovanezrin** [KheyransaPashayeva/PragmatechFoundationProject#4]
[Bu](https://github.com/KheyransaPashayeva/PragmatechFoundationProject/tree/master/Works/porto) linkdə CSS faylları ayrıca "css" adlı qovluqda olmalıdır, şəkillər isə "img" adlı qovluqda ola bilər, yəni mütləq başqa bir qovluqda olmalıdır. Qovluq strukturu ilə bağlı  [bu](https://link.medium.com/EDT8laQmslb) məqalə sizin üçün faydalı ola bilər.

**Comment by KheyransaPashayeva** [comment]
Bu vaxta qədər xirda işlər görürdük deyə bezilərində qaydaya əməl etməmişəm amma indi lahiyəyə başlayacagım üçün bunlara riayət etməyə çalışacam.
