### ISSUE TITLE
Verdiyiniz suallara cavab

### ISSUE THREAD

**Issue by isbendiyarovanezrin** [KheyransaPashayeva/PragmatechFoundationProject#5]
[Bu](https://github.com/KheyransaPashayeva/PragmatechFoundationProject/blob/master/ProjectFrontEnd/GeoEco_com_sayt%C4%B1/home/index.html#L32) hissəni mən də sınadım, məndə də elə oldu. Yükləyib istifadə edin, düzələcək. Ya da başqa ikondan istifadə edin. Səlis keçidlər üçün isə [bu](https://www.tutorialrepublic.com/codelab.php?topic=faq&file=css-smooth-transition-of-link-color-on-mouse-hover), [bu](https://css-tricks.com/almanac/properties/t/transition/) və [bu](https://youtu.be/vXBKv0p7JHw) qaynaqlar sizin üçün faydalı ola bilər.

**Comment by KheyransaPashayeva** [comment]
yuklemek deyene nece edecem biraz aydinliq getirin zehmet olmasa

**Comment by KheyransaPashayeva** [comment]
birde hr tag var birde novbeti nav hissede search iconu qoymusam onun gorunusunde qalinliq var nece ince ede bilerem?

**Comment by isbendiyarovanezrin** [comment]
Şəkil kimi yükləyib istifadə edin.

**Comment by isbendiyarovanezrin** [comment]
Hansı hissəni deyirsiniz bilmirəm. Link verərək deyin hər şeyi.
