### ISSUE TITLE
<nav> teqindən istifadə edin

### ISSUE THREAD

**Issue by isbendiyarovanezrin** [KheyransaPashayeva/PragmatechFoundationProject#7]
[Bu](https://github.com/KheyransaPashayeva/PragmatechFoundationProject/blob/master/Works/porto/navbar.html#L17) hissədə `<section id="navbar"> . . . </section>`  yazmaqdansa birbaşa `<nav></nav>` teqini yaza bilərsiniz. Teq haqqında daha ətraflı [bu](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/nav) qaynaqdan oxuya bilərsiniz.

**Comment by KheyransaPashayeva** [comment]
aha tesekkurler nezere alacam
