### ISSUE TITLE
Şəkil adlarında boşluq olmamalıdır

### ISSUE THREAD

**Issue by isbendiyarovanezrin** [KheyransaPashayeva/PragmatechFoundationProject#9]
**[Şəkil adlarında](https://github.com/KheyransaPashayeva/PragmatechFoundationProject/tree/master/ProjectFrontEnd/GeoEco_com_sayt%C4%B1/home/images)** boşluq olmalı deyil və şəkil adı şəkli izah etməlidir, yəni adına baxanda nə olduğu bilinməlidir. Məsələn, belə "wide_fullhd_6869701842_d7138c1937_o.jpg" şəkil adı düzgün deyil.

**Comment by KheyransaPashayeva** [comment]
onlar numune ucun yuklenib silecem sayta olmasi lazim olan sekillere elime gelmeyib hele
